logging:
    level:
        org:
            hibernate:
                SQL: debug
server:
    port: 8091
spring:
    config:
        activate:
            on-profile: pro
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost/db_springboot_pro?useSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
