logging:
    level:
        org:
            hibernate:
                SQL: debug
server:
    port: 8090
spring:
    config:
      activate:
          on-profile: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost/db_springboot_dev?useSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
